---
title: "Practical uses of the 2024 and 2026 CMV ECOclusters"
date: "2026-09-05"
description: "Tools and tips for diagnosing CMV and HLA alleles and annotating repertoire TCRs"
jupyter: python3
---

Over the posts in this series, I've explored the 2026 CMV ECOcluster and, to some extent,
the 2024 version. I've pointed out some interesting quirks and given some examples of how to
bring these ECOclusters to bear on TCR repertoires.

This post wraps up all those observations with practical tools and advice for using the
2026 CMV ECOcluster for CMV and HLA diagnosis, and for combining
the two ECOclusters and using them to analyze TCR repertoires. Follow the links to the
original posts for more details.

## Diagnose CMV ([Post 5](https://cmvividly.com/posts/05-predict-cmv-hla-emerson/))

You can use the 2026 CMV ECOcluster to predict CMV status from a repertoire just by
dividing the number of ECOcluster-matched TCRs
in a repertoire by the total number of repertoire TCRs. I built a simple
classifier into the CMVividly codebase, using simple repertoire breadth on the 2026 CMV ECOcluster.
Here's the ROC curve on both Emerson 2026 cohorts combined:

```{python}
import pandas as pd
from cmvividly.dx.cmv_dx import CMV_BREADTH_ROC_FPR, CMV_BREADTH_ROC_TPR
from matplotlib import pyplot as plt
import seaborn as sns
from cmvividly.plots.style import set_style
set_style()

f, ax = plt.subplots()
sns.lineplot(x=CMV_BREADTH_ROC_FPR, y=CMV_BREADTH_ROC_TPR, ax=ax)
ax.set_title("CMV breadth ROC on both Emerson cohorts")
ax.set_ylabel("TPR")
ax.set_xlabel("FPR")
f.set_size_inches(5,5)
```

The classifier takes a pandas dataframe that must have a column called `tcr` with
the TCRB sequence in the Adaptive format (`CDR3AA+Vgene+Jgene`, and the genes
must be in Adaptive format, too). Here's an example of running it on one of the Emerson
repertoires.

```{python}
from cmvividly.dx.cmv_dx import BreadthCmvClassifier

# instantiate a classifier
breadth_cmv_classifier = BreadthCmvClassifier()

# Here I'm dummying up a fake repertoire for donor P00089.
# I've saved down the intersection of
# the 2026 ECOcluster with repertoire P00089.
# UPR_P00089 is the number of rows in that repertoire, so I'm dummying
# up the missing rows, which don't affect the classifier
from cmvividly.data.access import load_cmv_ecocluster_intersect_emerson
pdf_tcr_matches_2026 = load_cmv_ecocluster_intersect_emerson()
UPR_P00089 = 347237
sample_name = "P00089"
pdf_fake_P00089 = pdf_tcr_matches_2026[pdf_tcr_matches_2026.sample_name == sample_name]
pdf_fake_P00089["tcr"] = pdf_fake_P00089.tcr_ecocluster
n_rows_to_dummy = UPR_P00089 - len(pdf_fake_P00089)
pdf_fake_P00089 = pd.concat([pdf_fake_P00089, pd.DataFrame({"sample_name": [sample_name] * n_rows_to_dummy})])

cmv_breadth_P00089 = sum(pdf_tcr_matches_2026.sample_name == sample_name) / UPR_P00089

result = breadth_cmv_classifier.classify_repertoire(pdf_fake_P00089)
print(f"CMV prediction for {sample_name}:")

import json
print(json.dumps(result, indent=4))
```

The `prediction_confidence` returned by the classifier is the probability that the call is correct,
using the predictions and labels on the two Emerson cohorts:
PPV for positive predictions, NPV or negative predictions. 
The threshold is the maximum-F1 point ("upper-left-most point") of the ROC curve.

As noted in Post 5, the performance of the classifier varies somewhat by donor HLA type,
creating observable differences by donor race. And the classifier comes with a lot of caveats:
they've only been validated on these two cohorts, relatively high-depth PBMC Adaptive
bulk TCRB sequencing from a mix of Caucasian and Asian donors.

*Note: the folks who built [CMVerify](https://github.com/UcarLab/CMVerify)
essentially turned the 2024 CMV ECOcluster into a CMV classifier, too. If you're dealing
with single-cell RNA sequencing, CMVerify is a lot better characterized than this classifer is.*

## Predict HLA type for CMV+ donors ([Post 5](https://cmvividly.com/posts/05-predict-cmv-hla-emerson/))

Individual HLA-COclusters in the CMV ECOcluster can be used to predict donor HLA allele status
from TCR repertoires from (known or predicted) CMV+ donors for 12 HLA-A and B alleles with high
sensitivity and specificity. I've built simple breadth-based models
(just like the CMV classifier I built) using the ROC curves
derived in Post 5. 

Here's and example of running them all on one donor:

```{python}
from cmvividly.dx.hla_dx import AllHlaAlleleClassifierCmvPos

all_hla_classifier = AllHlaAlleleClassifierCmvPos()

pdf_fake_P00089 = pdf_tcr_matches_2026[pdf_tcr_matches_2026.sample_name == sample_name]
pdf_fake_P00089["tcr"] = pdf_fake_P00089.tcr_ecocluster
n_rows_to_dummy = UPR_P00089 - len(pdf_fake_P00089)
pdf_fake_P00089 = pd.concat([pdf_fake_P00089, pd.DataFrame({"sample_name": [sample_name] * n_rows_to_dummy})])

print("HLA allele predictions for CMV+ donor P00089:")
all_hla_classifier.classify_cmvpos_repertoire(pdf_fake_P00089)
```

Never run those classifiers on CMV- donors! They'll behave unpredictably (likely
give almost all negative calls). And these classifiers come with the same caveats as
the CMV classifier: only evaluated on high-depth bulk Adaptive bulk sequencing.

## Combining the 2024 and 2026 ECOclusters into one dataset

As I explored in [Post 3](https://cmvividly.com/posts/03-compare-2024-2026/),
the 2026 CMV ECOcluster has twice as many TCRs as 2024. It's much more Class II-dominated, and
it's clearly missing many valuable TCRs from the 2024 version. So, to bring these ECOclusters to bear on TCR repertoires, I recommend combining them.

I wrote a wrapper function to load the 2024 version, load the 2026 version, and combine them: `load_combined_2024_2026_cmv_ecoclusters`. That function:

* Drops TCR duplicates from the 2024 version (the 2026 version doesn't have duplicates)
* Adds columns describing which ECOcluster version(s) each TCR came from and what HLA allele it was associated with
* Accepts the 2026 HLA association when the two disagree
* Writes the combined ECOcluster to `data/processed/cmv_ecocluster_combined_2024_2026.tsv`

```{python}
# useful imports
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

import itables
import seaborn as sns
from cmvividly.plots.style import set_style
set_style()

import itables
itables.init_notebook_mode()

from cmvividly.data.access import load_combined_2024_2026_cmv_ecoclusters

pdf_cmv_ecocluster_merged = load_combined_2024_2026_cmv_ecoclusters()

print(f"TCRs in merged ECOcluster: {len(pdf_cmv_ecocluster_merged)}")
print("Columns: ")
print(", ".join(pdf_cmv_ecocluster_merged.columns))
print("TCR breakdown by HLA class and ECOcluster version:")
pd.crosstab(pdf_cmv_ecocluster_merged.ecocluster_source, pdf_cmv_ecocluster_merged.hla_class)
```

## Several groups of V genes (and one pair of J genes) should be treated as one when matching TCRs ([Post 4](https://cmvividly.com/posts/04-v-j-gene-groups/))

In the CMV ECOcluster, we often see
the same CDR3 with different V or J genes. Those mismatches are highly concentrated in a small
number of groups of V genes and a single pair of J genes, nearly always in the same V or J family.
That strongly suggests that TCRs in the CMV ECOcluster that have those often-"confused" V 
and J genes are performing the same role in the same binding solution.

I made a library method (`combine_indistinguishable_genes`) to make it easy to match the CMV ECOcluster
to a repertoire that way: just run `combine_indistinguishable_genes` on both the ECOcluster dataframe
and the repertoire dataframe, then match on the new `tcr` column in both dataframes 
(both columns must be Adaptive-format TCRs).

## Annotate the CMV ECOcluster TCRs with IEDB ([Post 7](https://cmvividly.com/posts/07_iedb/))

I demonstrated that the CMV ECOcluster TCR intersection with IEDB (on V family + CDR3)
is strongly enriched for CMV-annotated TCRs.
I consider these peptide associations to be far more valid for repertoire annotation
than most of IEDB: the TCRs have two orthogonal associations with CMV
(experimental and statistical), and the ECOcluster association implies that, 
when the TCR is observed in a repertoire, it is usually responding to the CMV peptide
and not some other peptide.

Those annotations could be propagated among sequence clusters, but of course you'd need
some notion of sequence neighbors....

## Make "fuzzy" matches between ECOcluster TCRs and repertoire TCRs ([Post 6](https://cmvividly.com/posts/06_cdr3_1hamming/))

A single CDR3 amino acid swap, with the same V and J gene, is often thought of as the
"smallest possible" change to a TCR, unlikely to change TCR binding. I explored
those single swaps within the CMV ECOcluster and showed that they seem to be most
tolerated at (0-based) position 4.
Or, more accurately, at the first position after the positions determined by the TCR's V gene.

Limiting "fuzzy" matches to that position, and to the pairs of amino acids most often observed
to be swapped in the CMV ECOcluster, could cut down on the rate of false matching while
retaining most "real" matches.
